version: '3'
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name : ${PROJECT_NAME}
    environment:
      - CLOUDFLARE_TOKEN=${CLOUDFLARE_TOKEN}
    command: tunnel --no-autoupdate run --token $CLOUDFLARE_TOKEN
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      