# Please run these commands after docker-compose up -d:
# docker exec -ti miniflux /usr/bin/miniflux -migrate
# docker exec -ti miniflux /usr/bin/miniflux -create-admin

version: '3'
services:
  miniflux:
    image: miniflux/miniflux:latest
    container_name: 'miniflux'
    ports:
      - "8490:8080"
    expose:
        - 8490
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
      - VIRTUAL_HOST=miniflux.techromantica.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=miniflux.techromantica.com
  db:
    image: postgres:11
    container_name: 'postgres_miniflux'
    environment:
      - POSTGRES_DB=miniflux
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:  

networks:
    default:
        external:
            name: nginx-proxy
