version: '3'

services:
    vaultwarden:
        container_name: "vaultwarden"
        image: 'vaultwarden/server:latest'

        ports:
            - '8483:80'

        volumes:
            - "data:/data"

        environment:
            ADMIN_TOKEN=${ADMIN_TOKEN}

        restart: unless-stopped

volumes:
    data:

