version: '3'

services:
    app:
        container_name: "vaultwarden"
        image: 'vaultwarden/server:latest'

        ports:
            - ${HOST_PORT}:80

        environment:
            - ADMIN_TOKEN=${ADMIN_TOKEN}
            - TZ="Asia/Kolkata"

        volumes:
            - "data:/data"

        restart: unless-stopped

volumes:
    data:

