version: '3'

services:
  app:
    image: 'vaultwarden/server:latest'
    container_name: ${PROJECT_NAME}

    ports:
      - ${HOST_PORT}:80

    environment:
      - DOMAIN:${DOMAIN}
      - ADMIN_TOKEN:${ADMIN_TOKEN}

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - "data:/data"

    restart: unless-stopped

volumes:
  data:


