# Please use this command to generate the .env file with UID and GID:
# cat default.env | sed 's/UID=1001/UID='$(id -u)'/' | sed 's/GID=1001/GID='$(id -g)'/' > .env

version: "3"

services:
  server:
    image: gitea/gitea:latest

    environment:
      - USER_UID=${UID}
      - USER_GID=${GID}

    labels:
      - docker-volume-backup.stop-during-backup=${COMPOSE_PROJECT_NAME}

    restart: unless-stopped

    volumes:
      - data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    ports:
      - "${HOST_PORT}:3000"
      - "${HOST_SSH_PORT}:22"

  backup:
    image: offen/docker-volume-backup:latest
    restart: unless-stopped
    env_file: ./backup.env

    environment:
      - AWS_S3_PATH=${COMPOSE_PROJECT_NAME}
      - BACKUP_STOP_CONTAINER_LABEL=${COMPOSE_PROJECT_NAME}

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./notifications.tmpl:/etc/dockervolumebackup/notifications.d/notifications.tmpl
      - data:/backup/data:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /${HOME}/backups/${COMPOSE_PROJECT_NAME}:/archive

volumes:
  data:
  timezone:
  localtime:

