version: "3"

services:
  db:
    image: postgres:alpine
    container_name: ${PROJECT_NAME}-DB
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - db:/var/lib/postgresql

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_ROOT_PASSWORD=${POSTGRES_ROOT_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  app:
    image: nextcloud:latest
    container_name: ${PROJECT_NAME}-app
    restart: unless-stopped
    ports:
      - ${HOST_PORT}:80
    links:
      - db
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      #      - nextcloud:/var/www/html
      #      - apps:/var/www/html/custom_apps
      - config:/var/www/html/config
      - data:/var/www/html/data
      - theme:/var/www/html/themes

    environment:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db

volumes:
  #  nextcloud:
  #  apps:
  config:
  data:
  theme:
  db:


