version: '3'

services:
  app:
    image: 'ubuntu/squid'
    container_name: ${PROJECT_NAME}
    ports:
      - ${HOST_PORT}:51973

    volumes:
      - './squid.conf:/etc/squid/squid.conf'
    restart: unless-stopped
