version: '3'

services:
  app:
    image: sissbruecker/linkding:latest
    container_name: "linkding"
    ports:
      - "${HOST_PORT:-9090}:9090"

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - "data:/etc/linkding/data"
    restart: unless-stopped

volumes:
  data:
