version: "3"

services:
  app:
    image: portainer/portainer-ce
    container_name: ${PROJECT_NAME}

    ports:
      - ${HOST_DEFAULT_PORT}:8000
      - ${HOST_ADMIN_PORT}:9000

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - "data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
    data:
