version: '3'

services:
  app:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: ${PROJECT_NAME}

    ports:
      - ${HOST_HTTP_PORT}:80
      - ${HOST_HTTPS_PORT}:443
      - ${HOST_MAIN_PORT}:81

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - "data:/data"
      - "letsencrypt:/etc/letsencrypt"

    restart: unless-stopped

volumes:
  data:
  letsencrypt:


